### ISSUE TITLE
Restructure dish data to remove unnecessary data and support new features

### ISSUE THREAD

**Issue by HarveyPeachey** [HarveyPeachey/poke-quest-recipes#3]
**Is your feature request related to a problem? Please describe.**
Currently the [dish data](https://github.com/HarveyPeachey/poke-quest-recipes/blob/master/src/Dishes.js) is very bloated and needs restructuring based on the basic set of requirements shown in user stories to produce enough data for the front-end to display, whilst also conforming to an organised and readable structure.

**Describe the solution you'd like**

- [x] 1.  The first [user story](https://github.com/HarveyPeachey/poke-quest-recipes/projects/1#card-41629137) will require restructuring each individual variation of dish data to tie the `quality` of the recipe, with the group of `pokemon` that can be attracted.

- [ ] 2. The [second user story](https://github.com/HarveyPeachey/poke-quest-recipes/projects/1#card-41628958) will require a check that looks up the individual pokemon that is being filtered against each quality category for that dish, which can have a max of 4. Those being `Special`, `Very Good`, `Good` and `Normal`. And is ordered by descending order.

- [ ] 3. The third [user story](https://github.com/HarveyPeachey/poke-quest-recipes/projects/1#card-41626510) will require the most work. This feature will need to calculate the best variations of the dish to display, based on quality of the individual ingredients used for the recipe. This would mean each ingredient needs a weighting/rarity value.

**Describe alternatives you've considered**

**Testing notes**
This feature is expected to need manual testing.

**Additional context**
